### ISSUE TITLE
I have a problem with new version

### ISSUE THREAD

**Issue by Felleus** [PlayerNguyen/OptEco#13]
What do i do??
Help me please. This plugin is not work.

[12:16:41 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: opteco)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1010)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1022)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.throwex(DB.java:987)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.prepare(DB.java:264)
>.... [12:16:41 WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccount(SQLAccountDatabase.java:191)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccountInformation(SQLAccountDatabase.java:45)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.hasAccount(SQLAccountDatabase.java:135)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.OptEcoCacheAccountManager.add(OptEcoCacheAccountManager.java:75)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.listener.OptEcoPlayerListener.onPlayerJoinEvent(OptEcoPlayerListener.java:20)
>.... [12:16:41 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source)
>.... [12:16:41 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [12:16:41 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [12:16:41 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [12:16:41 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [12:16:41 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:16:41 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: opteco)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1010)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1022)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.throwex(DB.java:987)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.prepare(DB.java:264)
>.... [12:16:41 WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccount(SQLAccountDatabase.java:191)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.getAccountIdentify(SQLAccountDatabase.java:58)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.save(SQLAccountDatabase.java:75)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccountInformation(SQLAccountDatabase.java:48)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.hasAccount(SQLAccountDatabase.java:135)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.OptEcoCacheAccountManager.add(OptEcoCacheAccountManager.java:75)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.listener.OptEcoPlayerListener.onPlayerJoinEvent(OptEcoPlayerListener.java:20)
>.... [12:16:41 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source)
>.... [12:16:41 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [12:16:41 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [12:16:41 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [12:16:41 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [12:16:41 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:16:41 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: opteco)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1010)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1022)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.throwex(DB.java:987)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.prepare(DB.java:264)
>.... [12:16:41 WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.save(SQLAccountDatabase.java:87)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccountInformation(SQLAccountDatabase.java:48)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.hasAccount(SQLAccountDatabase.java:135)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.OptEcoCacheAccountManager.add(OptEcoCacheAccountManager.java:75)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.listener.OptEcoPlayerListener.onPlayerJoinEvent(OptEcoPlayerListener.java:20)
>.... [12:16:41 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source)
>.... [12:16:41 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [12:16:41 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [12:16:41 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [12:16:41 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [12:16:41 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:16:41 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: opteco)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1010)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1022)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.throwex(DB.java:987)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.prepare(DB.java:264)
>.... [12:16:41 WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccount(SQLAccountDatabase.java:191)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccountInformation(SQLAccountDatabase.java:45)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.OptEcoCacheAccountManager.add(OptEcoCacheAccountManager.java:76)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.listener.OptEcoPlayerListener.onPlayerJoinEvent(OptEcoPlayerListener.java:20)
>.... [12:16:41 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source)
>.... [12:16:41 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [12:16:41 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [12:16:41 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [12:16:41 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [12:16:41 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:16:41 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: opteco)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1010)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1022)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.throwex(DB.java:987)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.prepare(DB.java:264)
>.... [12:16:41 WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccount(SQLAccountDatabase.java:191)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.getAccountIdentify(SQLAccountDatabase.java:58)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.save(SQLAccountDatabase.java:75)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccountInformation(SQLAccountDatabase.java:48)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.OptEcoCacheAccountManager.add(OptEcoCacheAccountManager.java:76)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.listener.OptEcoPlayerListener.onPlayerJoinEvent(OptEcoPlayerListener.java:20)
>.... [12:16:41 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source)
>.... [12:16:41 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [12:16:41 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [12:16:41 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [12:16:41 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [12:16:41 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [12:16:41 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: opteco)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1010)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1022)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.throwex(DB.java:987)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
>.... [12:16:41 WARN]: at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
>.... [12:16:41 WARN]: at org.sqlite.core.DB.prepare(DB.java:264)
>.... [12:16:41 WARN]: at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
>.... [12:16:41 WARN]: at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
>.... [12:16:41 WARN]: at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
>.... [12:16:41 WARN]: at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.save(SQLAccountDatabase.java:87)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.SQLAccountDatabase.requestAccountInformation(SQLAccountDatabase.java:48)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.account.OptEcoCacheAccountManager.add(OptEcoCacheAccountManager.java:76)
>.... [12:16:41 WARN]: at me.playernguyen.opteco.listener.OptEcoPlayerListener.onPlayerJoinEvent(OptEcoPlayerListener.java:20)
>.... [12:16:41 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source)
>.... [12:16:41 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [12:16:41 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [12:16:41 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [12:16:41 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [12:16:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [12:16:41 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by PlayerNguyen** [comment]
Hello, Nextler.
This error is a critical one and I need to find out what the problem is. In this time, you can roll down to 2.0.1b.
It's very nice if you can give me some information about the problem like your config(without SQL Setting), your OS, ...

I'll do the best! Thanks for reporting

**Comment by Felleus** [comment]
E5-1650 v3 CPU, 5GB DDR4 RAM, SSD Storage, amd64 Linux, Java 1.8.0(242)

Update:
  CheckForUpdate: true
checkForUpdate: true
debug: false
language: lang
settings:
  startBalance: 0.0
  minimumBalance: -15.0
  timeToConfirmPayment: 10
  currencySymbol: EURO
  storeType: SQLITE
  sqlite:
    fileName: account.sqlite
  mysql:
    host: localhost
    database: dbname
    port: '3306'
    username: root
    password: ''
  sql:
    accountTable: opteco
    transactTable: opteco_transaction
    connectionPool:
      timeout: 60
  countdown:
    enable: true
    type: message
Settings:
  CurrencySymbol: ps
  Storage:
    Type: SQLITE
  Debug: false
  Preferences:
    MinimumCanTransact: 0.1
    Cache:
      RefreshTime: 5
    BeginPoint: 0.0
    MinimumReachPoint: -15.0
    LimitTopCommand: 5
    Language: language.yml
  SQL:
    SQLite:
      File: account.sqlite
    ConnectionPool:
      Timeout: 60
    MySQL:
      Host: localhost
      Database: dbname
      Port: '3306'
      Username: root
      Password: ''
    Table:
      Accounts: opteco
      Transactions: opteco_transaction
  Payment:
    Pending:
      Duration: 15
      Countdown:
        Enable: true
        Type: message

**Comment by PlayerNguyen** [comment]
The new 2.0.3b update will fix this.
