### ISSUE TITLE
Feature Request - ShopGuiPlus

### ISSUE THREAD

**Issue by mesl** [PlayerNguyen/OptEco#15]
After looking for a while I have finally found your plugin, the ultimate solution because I want to edit the money values directly in the database using PHP as well, Though, I'd love ShopGuiPlus support because of the project I'm trying to create
Is this possible? I look forward to hearing back from you

Kind regards,
Merlyn

**Comment by PlayerNguyen** [comment]
Hi Merlyn,
First, thanks for choosing my plugin. Second, I'll make a hook with ShopGuiPlus as fast as possible!
Excuse me whether my English was bad!
