### ISSUE TITLE
Feature Request - Rounding points.

### ISSUE THREAD

**Issue by ghost** [PlayerNguyen/OptEco#16]
Can you add a placeholder that returns the rounded point?
Like %opteco_points_rounded% return '5' instead of '5.0'.
Thanks,
Dustin

**Comment by PlayerNguyen** [comment]
So how about 5.1 or 5.xxx @dustindinh1412 ? It just is round to 5 huh?

**Comment by ghost** [comment]
Just rounded unnecessary part like ".0", 5.0 -> 5 "5.1" still "5.1".
