### ISSUE TITLE
Speed Up MySQL refresh rate?

### ISSUE THREAD

**Issue by iwentafk** [PlayerNguyen/OptEco#18]
**Describe the bug**
Whenever my players use BossShopPro and OptEco linked to a MySQL database for points, they can go negative if they were to spam click items, it takes more points than it should. This seems to be because it's not refreshing to MySQL fast enough.

**To Reproduce**
1. Use BossShop For Point Hook
2. Spam Click an item that accepts points.
3. Immediately type /points me and see your amount hasn't change.
4. Wait 5 seconds, ends up being way lower or going negative if you had a small amount of points.

**Expected behavior**
Should be fluid and take points immediately, instead of waiting for a long refresh rate.

**Comment by PlayerNguyen** [comment]
As a little trick, you can change the duration of the updater to make BossShopGui works smoother by edit this value to lower valuation. (This can be changed to 0 whether you want your Server requests the updater for every single change on Player money)
<img width="173" alt="Ảnh chụp Màn hình 2020-12-08 lúc 07 12 53" src="https://user-images.githubusercontent.com/10703461/101420580-1b541300-3925-11eb-8ba7-4dc060987afa.png">

**Comment by Hallowhead1** [comment]
This is an issue I am experiencing as well, allows players to buy more than they can actually afford and forces their balance below 0
