### ISSUE TITLE
ShopGUI+ Compatibility (Urgent please)

### ISSUE THREAD

**Issue by FrancyMak** [PlayerNguyen/OptEco#19]
**Is your feature request related to a problem? Please describe.**
Hi, the problem is that OptEco is the only plugin that supports Points with the features I need.
The only problem is that it is not compatbile with ShopGuiPlus.
This for me is a big problem because in Prison, if I used a plugin compatible with ShopGUI+ (Tokens or playerpoints which is deprecated) the command /token(s) would be occupied by TokenEnchants and Points are fundamental in my server.

**Describe the solution you'd like**
Add ShopGUI+ compatibility

**Describe alternatives you've considered**
Can't find it

**Comment by PlayerNguyen** [comment]
I'm still working on it! Please wait for the new update 🚀
