### ISSUE TITLE
ShopGUI+ Bugg hook

### ISSUE THREAD

**Issue by Teyir** [PlayerNguyen/OptEco#22]
**Describe the bug**
Hello,

I use ShopGUI+ et opteco, with your latest update ShopGUI+ don't use VAULT but OptECO.

When a player buy or sell an item the plugin don't use ShopGUI+ but OptECO.

**To Reproduce**
On my ShopGUI+ settings I have set this : `economyType: VAULT`

**Expected behavior**
I have talk with the ShopGUI+ dev about this bugg.
This is our conversation:

> Hey , it sounds like a bug on OptEco's end, please contact them instead
> There's no direct hook to OptEco in ShopGUI+ while OptEco itself hooks into SG+
> If they need any assistance from us regarding SG+ api please redirect them directly to me/this server

And this is a example of how to hook withe ShopGUI+ "CUSTOM" → https://github.com/MackenzieMolloy/MobCoins/tree/master/src/main/java/net/mackenziemolloy/MobCoins

Thank you very much for your help.

**Comment by PlayerNguyen** [comment]
Honestly, I didn't own the ShopGUI+ plugin. Therefore, I just use the API which ShopGUIPlus developer provide to me to develop so I don't really know about any bug.

**Comment by PlayerNguyen** [comment]
Plus, I'll try to fix it without testing-step. Last thing, farewell my dear user 🚀🐟.

**Comment by Bossbirdyman51** [comment]
Hi, The problem was fix ? Because i have the same problem ^^

**Comment by PlayerNguyen** [comment]
This issue was completely fixed in 2.1.2b.
