### ISSUE TITLE
YAML / SQLITE

### ISSUE THREAD

**Issue by ghost** [PlayerNguyen/OptEco#5]
hình như YAML tối ưu hơn SQLITE thì phải :v

**Comment by PlayerNguyen** [comment]
:v hỗ trợ cả 2 nhé

**Comment by PlayerNguyen** [comment]
Mà thấy mỗi cái nó có cái công dụng riêng à :>

**Comment by ghost** [comment]
:v nghe Beng Beng bảo là YAML tối ưu hơn 40%

**Comment by PlayerNguyen** [comment]
Than khảo thử xem hmmm
https://www.spigotmc.org/threads/yaml-vs-sql-sqlite.36159/

**Comment by ghost** [comment]
ok lmaoo good plugin anyway !!

**Comment by ghost** [comment]
nên thêm kiểu đếm ngược 5s mà không ./pay confirm thì hủy. good pl btw

**Comment by PlayerNguyen** [comment]
Uả có mà ta?
